-- ============================================================================
-- V2: Seed data — 10 customers, 6 warehouses (real US cities), 30 products,
-- and ~120 warehouse_stock rows. Stock distribution is intentionally uneven
-- so multi-item orders may have only one (or zero) eligible warehouses,
-- which exercises the 'single-warehouse fulfilment' rule.
-- ============================================================================

INSERT INTO customers (email, full_name) VALUES
  ('alice@example.com', 'Alice Johnson'),
  ('bob@example.com', 'Bob Smith'),
  ('carol@example.com', 'Carol Williams'),
  ('david@example.com', 'David Brown'),
  ('eve@example.com', 'Eve Davis'),
  ('frank@example.com', 'Frank Miller'),
  ('grace@example.com', 'Grace Wilson'),
  ('henry@example.com', 'Henry Moore'),
  ('isabella@example.com', 'Isabella Taylor'),
  ('jack@example.com', 'Jack Anderson');

INSERT INTO warehouses (code, name, latitude, longitude, address) VALUES
  ('WH-NYC', 'New York Distribution Center', 40.712776, -74.005974, '1 Warehouse Way, New York, NY 10001'),
  ('WH-LAX', 'Los Angeles Fulfilment Hub', 34.052235, -118.243683, '500 Logistics Blvd, Los Angeles, CA 90021'),
  ('WH-CHI', 'Chicago Midwest Hub', 41.878113, -87.629799, '200 Industrial Pkwy, Chicago, IL 60607'),
  ('WH-DAL', 'Dallas Regional Center', 32.776665, -96.796989, '800 Commerce St, Dallas, TX 75202'),
  ('WH-MIA', 'Miami Southeast Hub', 25.761681, -80.191788, '300 Port Rd, Miami, FL 33132'),
  ('WH-SEA', 'Seattle Pacific Hub', 47.606209, -122.332069, '700 Harbor Ave, Seattle, WA 98101');

INSERT INTO products (sku, name, unit_price) VALUES
  ('SKU-1001', 'Wireless Mouse', 24.99),
  ('SKU-1002', 'Mechanical Keyboard', 89.5),
  ('SKU-1003', '27" 4K Monitor', 349.0),
  ('SKU-1004', 'USB-C Hub 7-in-1', 45.0),
  ('SKU-1005', 'Noise Cancelling Headphones', 199.99),
  ('SKU-1006', 'Webcam 1080p', 59.9),
  ('SKU-1007', 'Standing Desk Mat', 34.5),
  ('SKU-1008', 'Ergonomic Office Chair', 299.0),
  ('SKU-1009', 'Laptop Stand Aluminum', 42.0),
  ('SKU-1010', 'Bluetooth Speaker', 79.99),
  ('SKU-1011', 'External SSD 1TB', 119.0),
  ('SKU-1012', 'Wireless Charger Pad', 29.99),
  ('SKU-1013', 'HDMI Cable 2m', 9.99),
  ('SKU-1014', 'Smart LED Bulb', 14.5),
  ('SKU-1015', 'Smart Home Hub', 99.0),
  ('SKU-1016', 'Action Camera 4K', 249.0),
  ('SKU-1017', 'Drone Mini', 399.0),
  ('SKU-1018', 'Fitness Tracker', 69.0),
  ('SKU-1019', 'Smartwatch Series X', 229.0),
  ('SKU-1020', 'E-Reader 7"', 139.0),
  ('SKU-1021', 'Tablet 10" Wi-Fi', 329.0),
  ('SKU-1022', 'Coffee Grinder Electric', 54.0),
  ('SKU-1023', 'Espresso Machine', 449.0),
  ('SKU-1024', 'Air Fryer 5L', 119.0),
  ('SKU-1025', 'Stand Mixer', 279.0),
  ('SKU-1026', 'Robot Vacuum', 349.0),
  ('SKU-1027', 'Cordless Drill', 89.0),
  ('SKU-1028', 'Yoga Mat 6mm', 24.0),
  ('SKU-1029', 'Resistance Band Set', 19.5),
  ('SKU-1030', 'Water Bottle Insulated 1L', 18.99);

INSERT INTO warehouse_stock (warehouse_id, product_id, quantity) VALUES
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1001'), 62),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1001'), 40),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1001'), 193),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1002'), 156),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1002'), 113),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1002'), 13),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1003'), 134),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1003'), 159),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1003'), 11),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1004'), 119),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1004'), 155),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1004'), 76),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1004'), 6),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1005'), 44),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1005'), 60),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1005'), 200),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1005'), 91),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1006'), 96),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1006'), 93),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1006'), 159),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1007'), 146),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1007'), 80),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1007'), 165),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1007'), 163),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1007'), 97),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1008'), 63),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1008'), 79),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1008'), 25),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1008'), 64),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1009'), 167),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1009'), 98),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1009'), 46),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1010'), 160),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1010'), 167),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1010'), 48),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1010'), 141),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1010'), 191),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1011'), 168),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1011'), 181),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1011'), 147),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1011'), 61),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1012'), 73),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1012'), 21),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1012'), 59),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1012'), 150),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1012'), 188),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1013'), 41),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1013'), 72),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1013'), 40),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1013'), 68),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1013'), 195),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1014'), 97),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1014'), 61),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1014'), 40),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1014'), 135),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1014'), 131),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1015'), 165),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1015'), 45),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1015'), 179),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1016'), 146),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1016'), 7),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1016'), 179),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1016'), 189),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1016'), 34),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1016'), 179),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1017'), 45),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1017'), 121),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1017'), 5),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1017'), 189),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1017'), 189),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1018'), 168),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1018'), 134),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1018'), 160),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1018'), 55),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1018'), 44),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1019'), 130),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1019'), 9),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1019'), 33),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1019'), 97),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1019'), 83),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1020'), 192),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1020'), 129),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1020'), 22),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1020'), 199),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1021'), 140),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1021'), 160),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1021'), 113),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1021'), 59),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1022'), 171),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1022'), 100),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1022'), 117),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1022'), 137),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1023'), 155),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1023'), 146),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1023'), 63),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1023'), 155),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1023'), 61),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1023'), 6),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1024'), 22),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1024'), 13),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1024'), 89),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1025'), 176),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1025'), 129),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1025'), 59),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1026'), 126),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1026'), 109),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1026'), 53),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1026'), 29),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1027'), 113),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1027'), 110),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1027'), 124),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1028'), 108),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1028'), 191),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1028'), 91),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1029'), 142),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1029'), 119),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1029'), 40),
  ((SELECT id FROM warehouses WHERE code='WH-LAX'), (SELECT id FROM products WHERE sku='SKU-1030'), 145),
  ((SELECT id FROM warehouses WHERE code='WH-CHI'), (SELECT id FROM products WHERE sku='SKU-1030'), 30),
  ((SELECT id FROM warehouses WHERE code='WH-DAL'), (SELECT id FROM products WHERE sku='SKU-1030'), 17),
  ((SELECT id FROM warehouses WHERE code='WH-NYC'), (SELECT id FROM products WHERE sku='SKU-1030'), 171),
  ((SELECT id FROM warehouses WHERE code='WH-MIA'), (SELECT id FROM products WHERE sku='SKU-1030'), 143),
  ((SELECT id FROM warehouses WHERE code='WH-SEA'), (SELECT id FROM products WHERE sku='SKU-1030'), 8);
